"""
macd.py
"""

import pandas as pd

from .indicator import Indicator, Signal


class MACD(Indicator):
    """
    calculate convergence/divergence
    tested with k_period=12 d_period=26, t_period=9
    https://www.alpharithms.com/calculate-macd-python-272222/
    The MACD’s popularity among technical traders can be attributed to
    its ease of interpretation and long-standing success rates.
    As with any technical indicator, the MACD is best used alongside other
    indicators to maximize the probability of generating a valid trade signal.
    Combining the MACD with other signals such as the Simple Moving Average (SMA)
    to help identify resistance and support levels is one popular combo.
    Another long-standing approach is to use the MACD and the Relative Strength Index (RSI)
    in tandem to reinforce the signals generated by either.
    """

    def __init__(self, k_period: int, d_period: int, t_period: int) -> None:
        self.window_k = k_period
        self.window_d = d_period
        self.window_t = t_period

    def signal(self, df: pd.DataFrame) -> Signal:
        # Get the 12-day (fast/k) EMA of the closing price
        k = (
            df["Close"]
            .ewm(span=self.window_k, adjust=False, min_periods=self.window_k)
            .mean()
        )

        # Get the 26-day (slow/d) EMA of the closing price
        d = (
            df["Close"]
            .ewm(span=self.window_d, adjust=False, min_periods=self.window_d)
            .mean()
        )

        # Subtract the 26-day EMA from the 12-Day EMA to get the MACD
        macd = k - d

        # Get the 9-Day EMA of the MACD for the Trigger line
        macd_s = macd.ewm(
            span=self.window_t, adjust=False, min_periods=self.window_t
        ).mean()

        # Calculate the difference (MACD - Trigger) for the Convergence/Divergence value
        macd_h = macd - macd_s

        # Add all of our new values for the MACD to the dataframe
        df["MACD"] = macd  # MACD slow d
        df["MACD_S"] = macd_s  # MACD fast k signal
        df["MACD_H"] = macd_h  # MACD convergence/divergence (buying pressure?)

        if df["MACD"].iloc[-1] > df["MACD_S"].iloc[-1]:
            return Signal.BUY
        elif df["MACD"].iloc[-1] < df["MACD_S"].iloc[-1]:
            return Signal.SELL
        else:
            return Signal.HOLD
